image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      cargo fetch
      make build test
    command: |
      gp ports await 23000 && gp open increment/src/lib.rs
      make build test
      soroban invoke --id 1 --wasm target/wasm32-unknown-unknown/release/soroban_increment_contract.wasm --fn increment
  - command: |
      echo Starting node to connect to Futurenet...
      docker run --rm -it -p "8000:8000" --name stellar stellar/quickstart:soroban-dev --enable-soroban-rpc --futurenet

vscode:
  extensions:
    - matklad.rust-analyzer
    - vadimcn.vscode-lldb

github:
  prebuilds:
    addBadge: true
    addComment: true
    pullRequests: true
    pullRequestsFromForks: true
